apiVersion: v1
kind: Service
metadata:
  namespace: bigbang-test
  name: bigbang-mysql
  labels:
    app: bigbang
spec:
  ports:
    - port: 3306
  selector:
    app: bigbang
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: bigbang-test
  name: bigbang-mysql
  labels:
    app: bigbang
spec:
  selector:
    matchLabels:
      app: bigbang
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bigbang
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql