apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bigbang-test
  name: mongo-pv-claim
  labels:
    app: bigbang
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      alicloud-pvname: mongo-pv-test
  storageClassName: nas
  volumeName: mongo-pv-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bigbang-test
  name: mysql-pv-claim
  labels:
    app: bigbang
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      alicloud-pvname: mysql-pv-test
  storageClassName: nas
  volumeName: mysql-pv-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bigbang-test
  name: mysql-data-pv-claim
  labels:
    app: bigbang
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      alicloud-pvname: mysql-data-pv-test
  storageClassName: nas
  volumeName: mysql-data-pv-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bigbang-test
  name: redis-data-pv-claim
  labels:
    app: bigbang
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      alicloud-pvname: redis-data-pv-test
  storageClassName: nas
  volumeName: redis-data-pv-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bigbang-test
  name: redis-pv-claim
  labels:
    app: bigbang
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      alicloud-pvname: redis-pv-test
  storageClassName: nas
  volumeName: redis-pv-test
