apiVersion: v1
kind: Service
metadata:
  name: bigbang-mysql
  labels:
    app: bigbang
spec:
  ports:
    - port: 3306
  selector:
    app: bigbang
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bigbang-mysql
  labels:
    app: bigbang
spec:
  selector:
    matchLabels:
      app: bigbang
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bigbang
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-data
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-init-data
        persistentVolumeClaim:
          claimName: mysql-data-pv-claim