apiVersion: v1
kind: Service
metadata:
  name: bigbang-mongo
  labels:
    app: bigbang
spec:
  ports:
    - port: 27017
  selector:
    app: bigbang
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bigbang-mongo
  labels:
    app: bigbang
spec:
  selector:
    matchLabels:
      app: bigbang
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bigbang
        tier: mongo
    spec:
      containers:
      - image: mongo:3.2.21
        name: mongo
        env:
        - name: "MONGO_DATA_DIR"
          value: "/data/db"
        - name: "MONGO_LOG_DIR"
          value: "/data/logs"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "rsvptech"
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-pass
        #       key: password
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
